spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/videodb
    username: ssar
    password: ssar
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 10
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mustache:
    servlet:
      expose-session-attributes: true
      expose-request-attributes: true
  application:
    name: video
