spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mustache:
    servlet:
      expose-session-attributes: true
      expose-request-attributes: true
  application:
    name: video
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true